#  ############################################################
#  # +------------------------------------------------------+ #
#  # |                   Jeep's Essentials                  | #
#  # +------------------------------------------------------+ #
#  ############################################################
#
#  Developed by: Jeeper_ (Jeeper#6808)
#
#  Color Choices:
#    Hex Code Example: <#FFFFFF>text</#FFFFFF>
#    Make sure to surround the text with its color and make sure it ends with a /!!
#
#    Minecraft Color Code Example: &aI'm typing in red!
#    This website has all the codes! https://www.digminecraft.com/lists/color_list_pc.php
#
#    Extra info on text formatting: https://docs.adventure.kyori.net/minimessage.html#the-components
#
#
#    ******* /essentials reload to reload files *******


#discord
Discord Link: https://discord.gg/tHfGcDQQQC
Discord Message: <#b8a567>Join our discord server! <#856f2d><discord>
Discord Bot Token: Classified
Punishment Channel ID: 0
Report Channel ID: 0

#chat
Chat Style: <prefix><#b8a567><player></#b8a567><suffix> <#856f2d>»</#856f2d> &7<message>
Join Message: '<#b8a567>[<#856f2d>+</#856f2d>] <player>'
First Join Message: '<#d1c59f><player> has joined for the first time! (#<number>)'
Leave Message: '<#b8a567>[<#856f2d>-</#856f2d>] <player>'
Broadcast Prefix: '<#856f2d>[<#7c3e12>Dirtlands</#7c3e12><#856f2d>] '
Player Death: '<#856f2d>☠ <message>'
Chat Cleared By Message: '<#b8a567>Chat cleared by <#b8a567><player></#b8a567>!'
Chat Muted By Message: '<#b8a567>Chat muted by <#b8a567><player></#b8a567>!'
Chat Unmuted By Message: '<#b8a567>Chat unmuted by <#b8a567><player></#b8a567>!'
Chat Is Muted: '<#b8a567>The chat is currently <#b8a567>muted</#b8a567>!'
Chat Color Set: '<#b8a567>Default chat color set'
Invalid Chat Color: '<#b8a567>That is not a valid chat color!'
Sending Messages Too Fast: '<#b8a567>You are sending "<#856f2d><message></#856f2d>" too fast! Slow down!'

#teleporting
Dont Move Message: '<#b8a567>Dont move or teleportation is <#856f2d>canceled'
Teleport Countdown: '<#b8a567>Teleporting to <location> in: <#856f2d><time>'
Teleport Canceled: '<#b8a567>Teleport <#856f2d>canceled</#856f2d>!'
Teleport Success: '<#b8a567>Successfully teleported to <#856f2d><location></#856f2d>!'

#spawn
Spawn Set: '<#856f2d>Spawn point set!'
Spawn Doesnt Exist: '<#b8a567>Spawn doesn''t exist yet! Make sure to set it with <#856f2d>/setspawn</#856f2d>!'

#warps
Warp Created: '<#856f2d>/warp <name> <#b8a567>was successfully created!'
Warp Deleted: '<#856f2d>/warp <name> <#b8a567>was successfully deleted!'
Warp List: '<#b8a567>Your current warps: <#856f2d><warps>'
Warp Doesnt Exist: '<#856f2d>/warp <name> <#b8a567>does not exist!'
No Warps: '<#b8a567>There are no warps!'

#homes
Home Created: '<#856f2d>/home <name> <#b8a567>was successfully created!'
Home Deleted: '<#856f2d>/home <name> <#b8a567>was successfully deleted!'
Home Doesnt Exist: '<#856f2d>/home <name> <#b8a567>does not exist!'
Too Many Homes: '<#b8a567>You''ve created too many homes! You can make up to <#856f2d><number>'
Home List: '<#b8a567>Your current homes: <#856f2d><homes>'
No Homes: '<#b8a567>You dont have any homes! Create one with <#856f2d>/sethome {name}</#856f2d>!'

#config
Essentials Reloaded: '<#856f2d>Essentials Reloaded!'

#nickname
Nickname Change: '<#b8a567>Your nickname has been set to <#856f2d><name><#b8a567>!'
Invalid Nickname: '<#856f2d>That is an invalid nickname!'
Nickname Not In Use: '<#b8a567>There are no players with the nickname <#856f2d><nickname>'
Players With Name: '<#b8a567>Players with the nickname <#856f2d><nickname></#856f2d>: <#856f2d><players>'

#commands
No Command Permission: '&cYou dont have permission to use this command!'
Player Only Command: '<#856f2d>You must be a player to execute this command!'
Player Doesnt Exist: '<#856f2d><player><#b8a567> doesn''t exist!'
Player Hasnt Logged In: '<#856f2d><player><#b8a567> has never logged in before!'
Player Is Offline: '<#856f2d><player><#b8a567> is offline!'
Correct Usage: '<#b8a567>Usage: <#856f2d><command>'
Command Cooldown: '<#b8a567>You can''t type this command for another <#856f2d><time></#856f2d>!'

#ignore
Ignore Success: '<#b8a567>You have successfully ignored <#856f2d><player></#856f2d>!'
Ignore List: '<#b8a567>Your current ignored players: <#856f2d><ignored>'
Ignoring Nobody: '<#b8a567>You are not ignoring anyone!'
Player Not Ignored: '<#b8a567>You are not ignoring <#856f2d><player></#856f2d>!'
Unignored: '<#b8a567>You have successfully unignored <#856f2d><player>'

#clear lag
Lag Time: '<#b8a567>Some entities will be cleared in <#856f2d><time></#856f2d>!'
Lag Cleared: '<#856f2d>Entities cleared!'

#teleport
Tphere Success: '<#b8a567>Successfully teleported <#856f2d><player></#856f2d> to your position'
Teleported to Player: '<#b8a567>You were teleported to <#856f2d><player></#856f2d>'

#tab
Tablist Header:
  First Line: <#b8a567>&l⛏ &r<#b8a567>[&r<#7c3e12>&lDirtlands&r<#b8a567>] &l■
  Second Line: ''
Tablist Footer:
  First Line: ''
  Second Line: <#d1c59f>⚔ <onlineplayers>/<maxplayers> Online ☠
Player Tab Style: '<prefix><#7c3e12><player> '

#afk
Player AFK: '<#b8a567><player><#d1c59f> is now AFK'
Player Not AFK: '<#b8a567><player><#d1c59f> is no longer AFK'

#powertool
Powertool Created: '<#856f2d>Powertool created with command <#856f2d><command></#856f2d>'

#tpa
Tpa Request Received: |-
  <#b8a567><player><#d1c59f><#d1c59f> has requested to teleport to you
  [<#b8a567><accept></#b8a567>] | [<#b8a567><deny></#b8a567>]
Tpa Request Sent: '<#b8a567><player><#d1c59f><#d1c59f> has been sent a teleport request'
No Tpa Request: '<#b8a567>You do not have a pending teleport request from <#856f2d><player></#856f2d>'
Tpa Request Denied: '<#b8a567><player><#d1c59f><#d1c59f> has denied your teleport request'
Tpa Successfully Denied: '<#d1c59f>You have successfully denied <#856f2d><player></#856f2d>''s teleport request'

#rules
Rules:
  - "<#169406>&m-----<#246b1a>--</#246b1a>-------<#47c945>-</#47c945>-----<#246b1a>--</#246b1a>&r <#7c3e12>Rules<#169406> &m-----<#47c945>---</#47c945>-------<#246b1a>--</#246b1a>----"
  - "<#856f2d>1.  <#b8a567>Racial <#856f2d>slurs</#856f2d> or any slurs in general are NOT allowed."
  - "<#856f2d>2.  <#b8a567>Harassing other players is not tolerated."
  - "<#856f2d>3.  <#b8a567>Any form of <#856f2d>exploit</#856f2d> will result in severe punishment."
  - "<#856f2d>4.  <#b8a567><#856f2d>Spamming</#856f2d> or bypassing <#856f2d>chat filters</#856f2d> is not allowed."
  - "<#856f2d>5.  <#b8a567>Joking about real world tragedies is not allowed."
  - "<#856f2d>6.  <#b8a567>Offensive jokes are <#856f2d>not allowed</#856f2d>."
  - "<#856f2d>7.  <#b8a567><#856f2d>Be respectful</#856f2d> towards staff and other Dirtlads."
  - "<#856f2d>8.  <#b8a567><#856f2d>Do not advertise</#856f2d> other servers here."
  - "<#856f2d>9.  <#b8a567>Do not join just to say <#856f2d>disrespectful</#856f2d> things."
  - "<#856f2d>10. <#b8a567>Do not ask for operator or staff positions."
  - "<#856f2d>11. <#b8a567>Nothing too explicit. (<#856f2d>NSFW</#856f2d> Skins, Builds, etc.)"
  - "<#856f2d>12. <#b8a567>Do not <#856f2d>evade</#856f2d> a ban. This will result in an <#856f2d>IP Ban</#856f2d>."
  - "<#856f2d>13. <#b8a567>Most importantly, <#856f2d>enjoy your time</#856f2d> here!"
  - "<#856f2d>&m-------------------------------------------------"

#memory
Memory Usage: '<#b8a567>Memory Usage: <#856f2d><memory> mb <#b8a567>/ <#856f2d><max> gb'
#tps
Tps Message: '<#b8a567>Server TPS from last 1m, 5m, 15m: [<#856f2d><1m><#b8a567>,</#b8a567> <5m><#b8a567>,</#b8a567> <15m><#b8a567>]'

#back
Back Message: '<#b8a567>Teleported to previous location!'
Cant Back: '<#b8a567>Previous location not found'

#report
Report Message: '<#b8a567>Thanks for the help, we will investigate the problem as soon as possible'
New Report: '<#b8a567><#856f2d>(#<number>) <reporter></#856f2d> has reported <#856f2d><reported></#856f2d> for <#856f2d><reason>'
Report Yourself: '<#b8a567>You can''t report yourself!'
Current Reports Join Message: '<#b8a567>There are <#856f2d><number></#856f2d> uninvestigated reports'

#punishments
Punishment Header: '<#b8a567>[&r<#7c3e12>&lDirtlands&r<#b8a567>]'
Ban Broadcast: '<#856f2d><player><#b8a567> has been banned for <#856f2d><reason></#856f2d>. (<time>)'
Ban No Reason Broadcast: '<#856f2d><player><#b8a567> has been banned. (<time>)'
IP Ban Broadcast: '<#856f2d><player><#b8a567> has been ip banned for <#856f2d><reason><#b8a567>.'
IP Ban No Reason Broadcast: '<#856f2d><player><#b8a567> has been ip banned.'
Unban Not Banned: '<#856f2d><player><#b8a567> is not banned.'
Player Unbanned: '<#856f2d><player><#b8a567> has been <#856f2d>unbanned</#856f2d>.'
Unmute Not Muted: '<#856f2d><player><#b8a567> is not muted.'
Player Unmuted: '<#856f2d><player><#b8a567> has been <#856f2d>unmuted</#856f2d>.'
Player Not IP Banned: '<#856f2d><player><#b8a567> is not ip unbanned.'
Player Un IP Banned: '<#856f2d><player><#b8a567> has had their <#856f2d>ip unbanned</#856f2d>.'
Issue Getting IP: '<#856f2d>There was an issue getting <#856f2d><player></#856f2d>''s IP address.'
Player Warned: '<#856f2d><player><#b8a567> has been <#856f2d>warned</#856f2d>.'
Warn Message No Reason: |-
  <#d1c59f>You have been warned. (Offense <#b8a567>#<offense></#b8a567>).
  On your <#b8a567>3rd</#b8a567> warning, you will be banned.
Warn Message: |-
  <#d1c59f>You have been warned for <#b8a567><reason></#b8a567>. (Offence <#b8a567>#<offense></#b8a567>).
  On your <#b8a567>3rd</#b8a567> warning, you will be banned.
Ban Message: |
  <#b8a567>You have been banned.

  Time: &r<#856f2d><time>

  &r<#b8a567>Appeal here: &r&n<#856f2d><discord>
Ban With Reason: |
  <#b8a567>You have been banned.


  Reason: &r<#856f2d><reason>
  &r<#b8a567>Time: &r<#856f2d><time>

  &r<#b8a567>Appeal here: &r&n<#856f2d><discord>
IP Ban Message: |
  <#b8a567>You have been Ip banned.

  Time: &r<#856f2d><time>

  &r<#b8a567>Appeal here: &r&n<#856f2d><discord>
IP Ban With Reason: |
  <#b8a567>You have been Ip banned.


  Reason: &r<#856f2d><reason>
  &r<#b8a567>Time: &r<#856f2d><time>

  &r<#b8a567>Appeal here: &r&n<#856f2d><discord>
Perm Ban Message: |
  <#b8a567>You have been banned <#856f2d>Permanently.


  &r<#b8a567>Appeal here: &r&n<#856f2d><discord>
Perm Ban With Reason: |
  <#b8a567>You have been banned <#856f2d>Permanently.

  <#b8a567>Reason: &r<#856f2d><reason>

  &r<#b8a567>Appeal here: &r&n<#856f2d><discord>
Punishment Time: '<#b8a567>Enter a time for the punishment. enter in format <#856f2d>0d 0h 0m<#b8a567>. Type "<#856f2d>Permanent<#b8a567>" for the punishment to last forever'
Punishment Reason: '<#b8a567>Enter a reason for the punishment'
Punishment Time Invalid: '<#b8a567>You entered an invalid time. Use the format <#856f2d>0d 0h 0m'
Permanent Mute No Reason: <#b8a567>You are currently muted <#b8a567>permanently
Permanent Mute With Reason: <#b8a567>You are currently muted for <#856f2d><reason><#b8a567>. You are muted <#856f2d>permanently<#b8a567>.
Muted No Reason: <#b8a567>You are currently muted for <#856f2d><time>
Muted With Reason: <#b8a567>You are currently muted for <#856f2d><reason><#b8a567>. (<#856f2d><time><#b8a567>)
Mute Successful No Reason: <#856f2d><player> <#b8a567>successfully muted for <#856f2d><time>
Mute Successful: <#856f2d><player> <#b8a567>successfully muted for <#856f2d><reason><#b8a567>. (<#856f2d><time><#b8a567>)
Kick Message: '<#b8a567>You have been kicked.'
Kick With Reason: |
  <#b8a567>You have been kicked.


  Reason: &r<#856f2d><reason>